development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  YELP_CONSUMER_KEY: <%= ENV["YELP_CONSUMER_KEY"] %>
  YELP_CONSUMER_SECRET: <%= ENV["YELP_CONSUMER_SECRET"] %>
  YELP_TOKEN: <%= ENV["YELP_TOKEN"] %>
  YELP_TOKEN_SECRET: <%= ENV["YELP_TOKEN_SECRET"] %>
  MANDRILL_USERNAME: <%= ENV["MANDRILL_USERNAME"] %>
  MANDRILL_PASSWORD: <%= ENV["MANDRILL_PASSWORD"] %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  YELP_CONSUMER_KEY: <%= ENV["YELP_CONSUMER_KEY"] %>
  YELP_CONSUMER_SECRET: <%= ENV["YELP_CONSUMER_SECRET"] %>
  YELP_TOKEN: <%= ENV["YELP_TOKEN"] %>
  YELP_TOKEN_SECRET: <%= ENV["YELP_TOKEN_SECRET"] %>
  MANDRILL_USERNAME: <%= ENV["MANDRILL_USERNAME"] %>
  MANDRILL_PASSWORD: <%= ENV["MANDRILL_PASSWORD"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  YELP_CONSUMER_KEY: <%= ENV["YELP_CONSUMER_KEY"] %>
  YELP_CONSUMER_SECRET: <%= ENV["YELP_CONSUMER_SECRET"] %>
  YELP_TOKEN: <%= ENV["YELP_TOKEN"] %>
  YELP_TOKEN_SECRET: <%= ENV["YELP_TOKEN_SECRET"] %>
  MANDRILL_USERNAME: <%= ENV["MANDRILL_USERNAME"] %>
  MANDRILL_PASSWORD: <%= ENV["MANDRILL_PASSWORD"] %>